services:
  - type: web
    name: careconnect-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: careconnect-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: careconnect-api
    env: node
    buildCommand: npm install
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: careconnect-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: careconnect-db
    databaseName: careconnect
    user: careconnect_user
    plan: free
