"use client";

import React, { useState } from "react";
import HabitTracker from "@/components/growth/HabitTracker";
import SkillDashboard from "@/components/growth/SkillDashboard";

const GrowthHubPage: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"habits" | "skills">("habits");

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <div className="container mx-auto p-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-extrabold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-pink-500 to-red-500">
            Personal Growth Hub
          </h1>
          <p className="text-xl text-gray-400 max-w-3xl mx-auto">
            Your comprehensive platform for skill development, habit building, and continuous learning.
            Track your progress, manage learning resources, and build lasting habits with AI-powered guidance.
          </p>
        </div>

        {/* Navigation Tabs */}
        <div className="flex justify-center mb-8">
          <div className="bg-gray-800 rounded-lg p-1">
            <button
              onClick={() => setActiveTab("habits")}
              className={`px-6 py-3 rounded-lg font-medium transition-colors ${
                activeTab === "habits"
                  ? "bg-purple-600 text-white"
                  : "text-gray-300 hover:text-white hover:bg-gray-700"
              }`}
            >
              📅 Habit Tracker
            </button>
            <button
              onClick={() => setActiveTab("skills")}
              className={`px-6 py-3 rounded-lg font-medium transition-colors ${
                activeTab === "skills"
                  ? "bg-purple-600 text-white"
                  : "text-gray-300 hover:text-white hover:bg-gray-700"
              }`}
            >
              🎯 Skill Development
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="max-w-7xl mx-auto">
          {activeTab === "habits" ? (
            <div>
              <div className="bg-gray-900 rounded-xl p-8 mb-8">
                <div className="text-center mb-8">
                  <div className="text-6xl mb-4">📅</div>
                  <h2 className="text-3xl font-bold mb-4">Habit Tracker</h2>
                  <p className="text-gray-400">
                    Build positive habits and track your daily progress. Click on any day to mark your habit as complete.
                  </p>
                </div>
                <HabitTracker />
              </div>
            </div>
          ) : (
            <div>
              <div className="bg-gray-900 rounded-xl p-8 mb-8">
                <div className="text-center mb-8">
                  <div className="text-6xl mb-4">🎯</div>
                  <h2 className="text-3xl font-bold mb-4">Skill Development</h2>
                  <p className="text-gray-400">
                    Define skills you want to learn, track your mastery level, and get AI-generated learning plans.
                  </p>
                </div>
                <SkillDashboard />
              </div>
            </div>
          )}
        </div>

        {/* Features Overview */}
        <div className="mt-16 bg-gray-900 rounded-xl p-8">
          <h2 className="text-3xl font-bold text-center mb-8 text-purple-300">Growth Hub Features</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="text-4xl mb-4">🤖</div>
              <h3 className="text-lg font-semibold mb-2">AI Learning Plans</h3>
              <p className="text-gray-400 text-sm">
                Get personalized, step-by-step learning plans generated by AI for any skill
              </p>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-4">📚</div>
              <h3 className="text-lg font-semibold mb-2">Resource Management</h3>
              <p className="text-gray-400 text-sm">
                Organize learning resources with AI-powered summaries and progress tracking
              </p>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-4">📊</div>
              <h3 className="text-lg font-semibold mb-2">Progress Tracking</h3>
              <p className="text-gray-400 text-sm">
                Visual progress tracking for both skills and habits with detailed analytics
              </p>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-4">🎯</div>
              <h3 className="text-lg font-semibold mb-2">Habit Building</h3>
              <p className="text-gray-400 text-sm">
                Build consistent habits with visual tracking and accountability features
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GrowthHubPage;
