apiVersion: v1
kind: Service
metadata:
  name: {{ include "steward-omni-max.fullname" . }}-web
  labels:
    {{- include "steward-omni-max.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "steward-omni-max.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "steward-omni-max.fullname" . }}-api
  labels:
    {{- include "steward-omni-max.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "steward-omni-max.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "steward-omni-max.fullname" . }}-broker
  labels:
    {{- include "steward-omni-max.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "steward-omni-max.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: broker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "steward-omni-max.fullname" . }}-docs
  labels:
    {{- include "steward-omni-max.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "steward-omni-max.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: docs
